config/routes.rb
Ontrack::Application.routes.draw do

  resources :groups


  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  resources :users
  resources :sessions

  resources :iterations

  resources :projects do
    resources :iterations
  end

  root :to => 'projects#index'

end

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  attr_accessible :description, :end_date, :name, :project_id, :start_date

  belongs_to :project
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  # GET /iterations
  # GET /iterations.json
  def index
    @iterations = Iteration.find_all_by_project_id(params[:project_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @iterations }
    end
  end

  # GET /iterations/1
  # GET /iterations/1.json
  def show
    @iteration = Iteration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @iteration }
    end
  end

  # GET /iterations/new
  # GET /iterations/new.json
  def new
    @iteration = Iteration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @iteration }
    end
  end

  # GET /iterations/1/edit
  def edit
    @iteration = Iteration.find(params[:id])
  end

  # POST /iterations
  # POST /iterations.json
  def create
    @iteration = Iteration.new(params[:iteration])

    respond_to do |format|
      if @iteration.save
        format.html { redirect_to @iteration, notice: 'Iteration was successfully created.' }
        format.json { render json: @iteration, status: :created, location: @iteration }
      else
        format.html { render action: "new" }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /iterations/1
  # PUT /iterations/1.json
  def update
    @iteration = Iteration.find(params[:id])

    respond_to do |format|
      if @iteration.update_attributes(params[:iteration])
        format.html { redirect_to @iteration, notice: 'Iteration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterations/1
  # DELETE /iterations/1.json
  def destroy
    @iteration = Iteration.find(params[:id])
    @iteration.destroy

    respond_to do |format|
      format.html { redirect_to iterations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/views/iterations/_form.html.erb
<%= form_for(@iteration) do |f| %>
  <% if @iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
      <% @iteration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iterations/edit.html.erb
<h1>Editing iteration</h1>

<%= render 'form' %>

<%= link_to 'Show', @iteration %> |
<%= link_to 'Back', iterations_path %>

app/views/iterations/index.html.erb
<h1>Listing iterations from Project: <%= @iterations.first.project.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @iterations.each do |iteration| %>
  <tr>
    <td><%= iteration.name %></td>
    <td><%= iteration.description %></td>
    <td><%= iteration.start_date %></td>
    <td><%= iteration.end_date %></td>
    <td><%= iteration.project_id %></td>
    <td><%= link_to 'Show', iteration %></td>
    <td><%= link_to 'Edit', edit_iteration_path(iteration) %></td>
    <td><%= link_to 'Destroy', iteration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Iteration', new_iteration_path %>

app/views/iterations/new.html.erb
<h1>New iteration</h1>

<%= render 'form' %>

<%= link_to 'Back', iterations_path %>

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @iteration.name %>
</p>

<p>
  <b>Description:</b>
  <%= @iteration.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @iteration.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @iteration.end_date %>
</p>

<p>
  <b>Project:</b>
  <%= @iteration.project_id %>
</p>


<%= link_to 'Edit', edit_iteration_path(@iteration) %> |
<%= link_to 'Back', iterations_path %>