config/routes.rb
Ontrack::Application.routes.draw do

  resources :groups


  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  resources :users
  resources :sessions

  resources :iterations

  resources :projects do
    resources :iterations
  end

  root :to => 'projects#index'

end

app/views/layouts/_header.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
			  <% if current_user %>
			    Logged in as <%= current_user.email %>
			    <%= link_to "Log out", log_out_path %>
			  <% else %>
			    <%= link_to "Sign up", sign_up_path %> or 
			    <%= link_to "Log in", log_in_path %>
	  		<% end %>
      </p>
    </nav>
    <%= link_to(image_tag("pruefung.png", alt: "G16", id: "logo"), root_url, title: "Dashboard") %>
   <%= yield :main_navigation %>
  </header>

app/views/layouts/_main_navigation.html.erb
<% content_for :main_navigation do %>
  <nav id="main_nav" role="navigation">
    <ul>
      <%= nav_tab('Home', root_path, current: current_tab) %>
      <%= nav_tab('Projects', projects_path, current: current_tab) %>
      <%= nav_tab('Groups', groups_path, current: current_tab) %>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    <% if content_for?(:title) %>
      ONTRACK: <%= yield :title %>
    <% else %>
      ONTRACK
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

  <%#= image_tag("tagline.png", alt: "Creative Project Management Made Easy", id: "tagline") %>
  <div class="container">
    <section id="content">
      <%# START:notifications %>
      <% if notice %>
        <p class="notification notice">
          <%= notice %>
        </p>
      <% end %>

      <% if alert %>
        <p class="notification alert">
          <%= alert %>
        </p>
      <% end %>
      <%# END:notifications %>
      <%= yield %>
    </section>

  </div>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2013 G16. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>